# Generated by Django 5.0 on 2023-12-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="BirthDate",
            field=models.DateField(auto_created=True, default="1990-01-01"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="City",
            field=models.CharField(default="", max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="Country",
            field=models.CharField(default="", max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="Gender",
            field=models.CharField(
                choices=[("m", "male"), ("f", "female")], default="", max_length=2
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="Pincode",
            field=models.CharField(default="", max_length=25, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="State",
            field=models.CharField(default="", max_length=25, null=True),
        ),
    ]
