# Generated by Django 5.0 on 2024-01-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizApp", "0002_userprofile_birthdate_userprofile_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="ProfileImage",
            field=models.FileField(default="avatar.png", upload_to="profile_images/"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="Gender",
            field=models.CharField(
                choices=[("m", "male"), ("f", "female")], default="", max_length=2
            ),
        ),
    ]
