# Generated by Django 5.0 on 2024-01-08 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizApp", "0003_userprofile_profileimage_alter_userprofile_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Category", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=100)),
                ("Duration", models.IntegerField(default=0)),
                (
                    "DifficultyLevel",
                    models.CharField(
                        choices=[("easy", "easy"), ("mid", "midium"), ("hrd", "hard")],
                        max_length=25,
                    ),
                ),
                ("TotalScore", models.IntegerField()),
                (
                    "RemarkLevel",
                    models.CharField(
                        choices=[
                            (25, "poor"),
                            (50, "average"),
                            (75, "good"),
                            (100, "excellent"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "UserProfile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quizApp.userprofile",
                    ),
                ),
                (
                    "Category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quizApp.quizcategory",
                    ),
                ),
                (
                    "Subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quizApp.subject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuesAns",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "QuesImage",
                    models.FileField(default="avatar.png", upload_to="ques_images/"),
                ),
                ("Question", models.TextField(max_length=2500)),
                ("Options", models.TextField(max_length=255)),
                ("IsMultiSelect", models.BooleanField(default=False)),
                ("Answer", models.CharField(max_length=25)),
                (
                    "Quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="quizApp.quiz"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuizPlay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Score", models.IntegerField()),
                ("Remark", models.CharField(max_length=10)),
                (
                    "QuesAns",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quizApp.quesans",
                    ),
                ),
                (
                    "UserProfile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quizApp.userprofile",
                    ),
                ),
            ],
        ),
    ]
