# Generated by Django 5.0 on 2024-01-08 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizApp", "0004_quizcategory_subject_quiz_quesans_quizplay"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quesans",
            options={"verbose_name_plural": "Ques n Answers"},
        ),
        migrations.AlterModelOptions(
            name="quiz",
            options={"verbose_name_plural": "Quizes"},
        ),
        migrations.AlterModelOptions(
            name="quizcategory",
            options={"verbose_name_plural": "Quiz Categories"},
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="RemarkLevel",
        ),
        migrations.RemoveField(
            model_name="quizplay",
            name="Remark",
        ),
        migrations.AddField(
            model_name="quizplay",
            name="RemarkLevel",
            field=models.CharField(
                choices=[
                    (25, "poor"),
                    (50, "average"),
                    (75, "good"),
                    (100, "excellent"),
                ],
                max_length=25,
            ),
            preserve_default=False,
        ),
    ]
