# Generated by Django 5.0 on 2024-01-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizApp", "0005_alter_quesans_options_alter_quiz_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizplay",
            name="RemarkLevel",
            field=models.CharField(
                choices=[
                    ("25", "poor"),
                    ("50", "average"),
                    ("75", "good"),
                    ("100", "excellent"),
                ],
                max_length=25,
            ),
        ),
    ]
